### ISSUE TITLE
cudamat.cudamat.CUDAMatException: CUBLAS error

### ISSUE THREAD

**Issue by sarehsh** [emansim/unsupervised-videos#1]
Hi there,

I'm trying to run the the first example using the MNIST dataset but it keeps crashing.

=================================================================
Using board 0
2048
Traceback (most recent call last):
  File "lstm_combo.py", line 398, in <module>
    main()
  File "lstm_combo.py", line 385, in main
    lstm_autoencoder = LSTMCombo(model)
  File "lstm_combo.py", line 18, in __init__
    self.lstm_stack_enc_.Add(lstm.LSTM(l))
  File "/Users/shirazis/Documents/Codes/unsupervised-videos/lstm.py", line 33, in __init__
    self.w_input_ = Param((4 * num_lstms, self.input_dims_), lstm_config.w_input)
  File "/Users/shirazis/Documents/Codes/unsupervised-videos/util.py", line 29, in __init__
    self.dw_ = cm.empty_like(self.w_)
  File "/Users/shirazis/Documents/Codes/unsupervised-videos/cudamat/cudamat.py", line 1883, in empty_like
    cmat = empty(m.shape)
  File "/Users/shirazis/Documents/Codes/unsupervised-videos/cudamat/cudamat.py", line 1872, in empty
    raise generate_exception(err_code)
cudamat.cudamat.CUDAMatException: CUBLAS error.
==================================================================

Can you please help me to figure out what's happening?

Cheers,
Sareh

**Comment by emansim** [comment]
I get this error when there is not enough memory on gpu to fit the matrices.

I would suggest to reduce the batch size. But it should also work with default settings on nvidia gpus with 6GB of memory.
