### ISSUE TITLE
Unable to open object (Object 'lstm_1_enc:w_dense' doesn't exist) during result visualization

### ISSUE THREAD

**Issue by Luna86** [emansim/unsupervised-videos#10]
When running the visualization code provided in README:
`python display_results.py models/lstm_combo_1layer_mnist_pretrained.pbtxt datasets/bouncing_mnist_valid.pbtxt 1`

The output shows a key error in the hdf5 dataset:
` File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2408)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2365)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py", line 166, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2408)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2365)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/tmp/pip_build_root/h5py/h5py/h5o.c:3456)`
`KeyError: "Unable to open object (Object 'lstm_1_enc:w_dense' doesn't exist)"
`

I have changed the directories to my local dir in the pbtxt files. Any clue what's happening here? Thanks!

**Comment by ArghyaPal** [comment]
Got the same problem..

@Luna86  have you solved this issue?

`
Using board 0
2048
Traceback (most recent call last):
  File "display_results.py", line 22, in <module>
    main()
  File "display_results.py", line 9, in main
    lstm_autoencoder = LSTMCombo(model)
  File "/home/arghya/unsupervised-videos/lstm_combo.py", line 18, in __init__
    self.lstm_stack_enc_.Add(lstm.LSTM(l))
  File "/home/arghya/unsupervised-videos/lstm.py", line 21, in __init__
    self.w_dense_  = Param((4 * num_lstms, num_lstms), lstm_config.w_dense)
  File "/home/arghya/unsupervised-videos/util.py", line 50, in __init__
    mat = f[config.dataset_name].value
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-4NvvlI/h5py/h5py/_objects.c:2682)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-4NvvlI/h5py/h5py/_objects.c:2640)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py", line 166, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-4NvvlI/h5py/h5py/_objects.c:2682)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-4NvvlI/h5py/h5py/_objects.c:2640)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/tmp/pip-build-4NvvlI/h5py/h5py/h5o.c:3568)
KeyError: "Unable to open object (Object 'lstm_1_enc:w_dense' doesn't exist)"
`

**Comment by JingHuang81** [comment]
Did you change the file_name in .phtxt to the name of output file in the model folder?
