### ISSUE TITLE
CUBLAS error

### ISSUE THREAD

**Issue by fahimeh62** [emansim/unsupervised-videos#14]
Hi,
I have a problem with running the code. when I tried :
python lstm_combo.py models/lstm_combo_1layer_mnist.pbtxt datasets/bouncing_mnist.pbtxt datasets/bouncing_mnist_valid.pbtxt 0
I got this error:

Using board 0
2048
2048
Traceback (most recent call last):
  File "lstm_combo.py", line 407, in <module>
    main()
  File "lstm_combo.py", line 394, in main
    lstm_autoencoder = LSTMCombo(model)
  File "lstm_combo.py", line 21, in __init__
    self.lstm_stack_dec_.Add(lstm.LSTM(l))
  File "/home/fahimeh/ProgramFiles/unsupervised-videos/lstm.py", line 21, in __init__
    self.w_dense_  = Param((4 * num_lstms, num_lstms), lstm_config.w_dense)
  File "/home/fahimeh/ProgramFiles/unsupervised-videos/util.py", line 29, in __init__
    self.dw_ = cm.empty_like(self.w_)
  File "/home/fahimeh/ProgramFiles/unsupervised-videos/cudamat/cudamat.py", line 1881, in empty_like
    cmat = empty(m.shape)
  File "/home/fahimeh/ProgramFiles/unsupervised-videos/cudamat/cudamat.py", line 1869, in empty
    raise generate_exception(err_code)
cudamat.cudamat.CUDAMatException: CUBLAS error.

Could you please help me to fix it?
Thanks a lot.

**Comment by emansim** [comment]
It looks like the GPU is out of memory and thats why it can't create cmat matrix. Trying reducing the number of hidden units in LSTM.

Which GPU are you using ?

**Comment by fahimeh62** [comment]
Thanks for reply.
Yes, you were right, I solved the memory problem and now after running the following script:

python lstm_combo.py models/lstm_combo_1layer_mnist.pbtxt datasets/bouncing_mnist.pbtxt datasets/bouncing_mnist_valid.pbtxt 1

I got this:
Using board 0
2048
2048
2048
Please set the correct path to MNIST dataset

I set correct path to trained weights in models/lstm_combo_1layer_mnist_pretrained.pbtxt and other files in models directory.
then I tried:

python display_results.py models/lstm_combo_1layer_mnist_pretrained.pbtxt datasets/bouncing_mnist_valid.pbtxt 1
but I got this error:

Using board 0
2048
Traceback (most recent call last):
  File "display_results.py", line 22, in <module>
    main()
  File "display_results.py", line 9, in main
    lstm_autoencoder = LSTMCombo(model)
  File "/home/fahimeh/ProgramFiles/unsupervised-videos/lstm_combo.py", line 18, in __init__
    self.lstm_stack_enc_.Add(lstm.LSTM(l))
  File "/home/fahimeh/ProgramFiles/unsupervised-videos/lstm.py", line 21, in __init__
    self.w_dense_  = Param((4 * num_lstms, num_lstms), lstm_config.w_dense)
  File "/home/fahimeh/ProgramFiles/unsupervised-videos/util.py", line 50, in __init__
    mat = f[config.dataset_name].value
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py-2.4.0/h5py/_objects.c:2405)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py-2.4.0/h5py/_objects.c:2362)
  File "/home/fahimeh/anaconda/lib/python2.7/site-packages/h5py/_hl/group.py", line 160, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py-2.4.0/h5py/_objects.c:2405)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py-2.4.0/h5py/_objects.c:2362)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (-------src-dir-------/h5py-2.4.0/h5py/h5o.c:3456)
KeyError: "Unable to open object (Object 'lstm_1_enc:w_dense' doesn't exist)"

Is that normal to get this error and how can  I fix it?
Thanks.

**Comment by emansim** [comment]
It is something to do with ctypes library build in into python.

We were using python 2.7 (i believe) for experiments so, newer versions of python might have made some changes to ctypes library that breaks the code.

**Comment by nainadhingra2012** [comment]
@fahimeh62 How did you resolve your error? I tried resolving it but unable to do so.
