### ISSUE TITLE
cudamat.cudamat.CUDAMatException: CUDA error: no error

### ISSUE THREAD

**Issue by tinarwhite** [emansim/unsupervised-videos#3]
I am using an Amazon Machine Image (AMI) to launch a GPU instance on Amazon EC2 with CUDA 7.5 and the required libraries installed. When I type make in your cudamat directory, everything appears to work. I am able to compile the .proto file and download the datasets. However, when I attempt to train a model, I get this error:

ubuntu@ip-172-31-9-162:~/unsupervised-videos-master$ python lstm_combo.py models/lstm_combo_1layer_mnist.pbtxt datasets/bouncing_mnist.pbtxt datasets/bouncing_mnist_valid.pbtxt 1
invalid device ordinal
Traceback (most recent call last):
File "lstm_combo.py", line 402, in <module>
board = LockGPU(board=board_id)
File "/home/ubuntu/unsupervised-videos-master/util.py", line 144, in LockGPU
cm.cuda_set_device(board)
File "/home/ubuntu/unsupervised-videos-master/cudamat/cudamat.py", line 2273, in cuda_set_device
raise generate_exception(err_code)
cudamat.cudamat.CUDAMatException: CUDA error: no error

Is your cudamat setup compatible with CUDA 7.5? Is it necessary to use your custom directory? 

Can you help me find the source of this error? I'd appreciate it very much. 

Best,
Tina

**Comment by tinarwhite** [comment]
I figured it out. The invalid device ordinal error means that you need to specify the correct ordinal and it should be 0 rather than 1. 

The fix on my instance is to run the commands with 0 instead of 1:
python lstm_combo.py models/lstm_combo_1layer_mnist.pbtxt datasets/bouncing_mnist.pbtxt datasets/bouncing_mnist_valid.pbtxt 0
