### ISSUE TITLE
libcudamat.so?

### ISSUE THREAD

**Issue by YantianZha** [emansim/unsupervised-videos#5]
Hi,

I tried to run lstm_combo.py, but I got the error: OSError: dlopen(/Users/yantian/Google Drive/Yantian/DL/unsupervised-videos-master/cudamat/libcudamat.so, 6): image not found

Where can I get libcudamat.so? Thank you in advance!

**Comment by emansim** [comment]
you need to go first inside cudamat folder and install it by running "make"

make sure to set correct path to relevant dependencies inside Makefile

**Comment by YantianZha** [comment]
Thanks a lot!

**Comment by YantianZha** [comment]
But after successfully complying CUDA, I still got an error:
![snip20160314_7](https://cloud.githubusercontent.com/assets/9017839/13762195/72331cc2-e9fa-11e5-94aa-e87cd78290c9.png)

I believe the error comes from the wrong configuration in Makefile. Since my graphics card, NVIDIA GTX 650, maybe different from yours. So here's my **unsuccessful trial**:
![snip20160314_8](https://cloud.githubusercontent.com/assets/9017839/13762225/a99c800e-e9fa-11e5-81ea-ab3806a28dbb.png)

Therefore, I suspect the way of editing the makefile was incorrect?

Thanks!

**Comment by YantianZha** [comment]
The complied .so files can't be used, so I think the way I edited MakeFile was wrong? My graphics card is GTX 650m, OS is mac. I've updated the issue on github. Thanks!


Best,

- Yantian


________________________________

**Comment by emansim** [comment]
You can see that the error says that the cuda toolkit version you are using is incompatible with your gpu GTX 650.

Which version of cuda toolkit you are using ? I would maybe suggest downgrading to older toolkits that support your gpu and changing the path to it in Makefile

**Comment by YantianZha** [comment]
Thanks! After a survey, I found I can't use CUDA 6.5 (with mac of EI Capitan). So I used CUDA 7.5. But it seems that I must use CUDA 6.5? Here is the error:

Traceback (most recent call last):
  File "/Users/yantian/Google Drive/Yantian/DL/unsupervised-videos-master/lstm_combo.py", line 1, in <module>
    from data_handler import *
  File "/Users/yantian/Google Drive/Yantian/DL/unsupervised-videos-master/data_handler.py", line 3, in <module>
    from util import *
  File "/Users/yantian/Google Drive/Yantian/DL/unsupervised-videos-master/util.py", line 3, in <module>
    import cudamat as cm
  File "/Users/yantian/Google Drive/Yantian/DL/unsupervised-videos-master/cudamat/__init__.py", line 1, in <module>
    from cudamat import *
  File "/Users/yantian/Google Drive/Yantian/DL/unsupervised-videos-master/cudamat/cudamat.py", line 11, in <module>
    _cudamat = ct.cdll.LoadLibrary(os.getcwd() + '/cudamat/libcudamat.so')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: dlopen(/Users/yantian/Google Drive/Yantian/DL/unsupervised-videos-master/cudamat/libcudamat.so, 6): Library not loaded: @rpath/libcublas.7.5.dylib
  Referenced from: /Users/yantian/Google Drive/Yantian/DL/unsupervised-videos-master/cudamat/libcudamat.so
  Reason: image not found

Thanks!
