### ISSUE TITLE
ImportError: No module named config_pb2,    what's the package name?

### ISSUE THREAD

**Issue by loveJasmine** [emansim/unsupervised-videos#7]
envy@ub1404:~/os_pri/github/unsupervised-videos$ python lstm_combo.py models/lstm_combo_1layer_mnist.pbtxt datasets/bouncing_mnist.pbtxt datasets/bouncing_mnist_valid.pbtxt 1
Traceback (most recent call last):
  File "lstm_combo.py", line 1, in <module>
    from data_handler import *
  File "/home/envy/os_pri/github/unsupervised-videos/data_handler.py", line 3, in <module>
    from util import *
  File "/home/envy/os_pri/github/unsupervised-videos/util.py", line 16, in <module>
    import config_pb2
ImportError: No module named config_pb2
envy@ub1404:~/os_pri/github/unsupervised-videos$

**Comment by springzfx** [comment]
you need to install a compiler to compile *.proto file.
